-- DMS user keybind overrides (edit via Control Center or dms; do not remove this header)

hl.unbind("CTRL + Escape")
hl.bind("CTRL + Escape", hl.dsp.exec_cmd("dms ipc call spotlight toggle"), { description = "dms ipc call spotlight toggle" })
hl.unbind("ALT + CTRL + Left")
hl.bind("ALT + CTRL + Left", hl.dsp.focus({ workspace = "e-1" }), { description = "focus workspace e-1" })
hl.unbind("ALT + CTRL + Right")
hl.bind("ALT + CTRL + Right", hl.dsp.focus({ workspace = "e+1" }), { description = "focus workspace e+1" })
hl.unbind("ALT + CTRL + SHIFT + Left")
hl.bind("ALT + CTRL + SHIFT + Left", hl.dsp.window.move({ workspace = "e-1" }), { description = "move to workspace e-1 (non-silent)" })
hl.unbind("ALT + CTRL + SHIFT + Right")
hl.bind("ALT + CTRL + SHIFT + Right", hl.dsp.window.move({ workspace = "e+1" }), { description = "move to workspace e+1 (non-silent)" })
hl.unbind("SUPER + Return")
hl.bind("SUPER + Return", hl.dsp.exec_cmd("kitty"), { description = "kitty" })
hl.unbind("SUPER + CTRL + down")
hl.unbind("SUPER + Page_Down")
hl.unbind("SUPER + Page_Up")
hl.unbind("SUPER + SHIFT + T")
hl.unbind("SUPER + T")
hl.unbind("SUPER + space")
hl.bind("SUPER + space", hl.dsp.window.float({ action = "toggle" }), { description = "Float/unfloat window" })
