-- DMS user keybind overrides (edit via Control Center or dms; do not remove this header)

hl.unbind("ALT + CTRL + L")
hl.bind("ALT + CTRL + L", hl.dsp.exec_cmd("dms ipc call lock lock"), { description = "dms ipc call lock lock" })
hl.unbind("CTRL + Escape")
hl.bind("CTRL + Escape", hl.dsp.exec_cmd("dms ipc call spotlight toggle"), { description = "dms ipc call spotlight toggle" })
hl.unbind("ALT + CTRL + Left")
hl.bind("ALT + CTRL + Left", hl.dsp.focus({ workspace = "e-1" }), { description = "focus workspace e-1" })
hl.unbind("ALT + CTRL + Right")
hl.bind("ALT + CTRL + Right", hl.dsp.focus({ workspace = "e+1" }), { description = "focus workspace e+1" })
hl.unbind("ALT + CTRL + SHIFT + Left")
hl.bind("ALT + CTRL + SHIFT + Left", hl.dsp.window.move({ workspace = "e-1" }), { description = "move to workspace e-1 (non-silent)" })
hl.unbind("ALT + CTRL + SHIFT + Right")
hl.bind("ALT + CTRL + SHIFT + Right", hl.dsp.window.move({ workspace = "e+1" }), { description = "move to workspace e+1 (non-silent)" })
hl.unbind("SUPER + 0")
hl.bind("SUPER + 0", hl.dsp.focus({ workspace = "10" }), { description = "focus workspace 10" })
hl.unbind("SUPER + SHIFT + 0")
hl.bind("SUPER + SHIFT + 0", hl.dsp.window.move({ workspace = "10" }))
hl.unbind("SUPER + SHIFT + equal")
hl.bind("SUPER + SHIFT + equal", hl.dsp.window.move({ workspace = "12" }))
hl.unbind("SUPER + SHIFT + minus")
hl.bind("SUPER + SHIFT + minus", hl.dsp.window.move({ workspace = "11" }))
hl.unbind("SUPER + equal")
hl.bind("SUPER + equal", hl.dsp.focus({ workspace = "12" }), { description = "focus workspace 12" })
hl.unbind("SUPER + minus")
hl.bind("SUPER + minus", hl.dsp.focus({ workspace = "11" }), { description = "focus workspace 11" })
hl.unbind("SUPER + KP_Add")
hl.bind("SUPER + KP_Add", hl.dsp.window.resize({ x = 100, y = 0, relative = true }), { repeating = true })
hl.unbind("SUPER + KP_Subtract")
hl.bind("SUPER + KP_Subtract", hl.dsp.window.resize({ x = -100, y = 0, relative = true }), { repeating = true })
hl.unbind("SUPER + Return")
hl.bind("SUPER + Return", hl.dsp.exec_cmd("kitty --directory ~"), { description = "kitty" })
hl.unbind("SUPER + ALT + L")
hl.unbind("SUPER + CTRL + down")
hl.unbind("SUPER + Page_Down")
hl.unbind("SUPER + Page_Up")
hl.unbind("SUPER + SHIFT + T")
hl.unbind("SUPER + T")
hl.unbind("SUPER + space")
hl.bind("SUPER + space", hl.dsp.window.float({ action = "toggle" }), { description = "Float/unfloat window" })
