#!/usr/bin/env bash

## Copyright (C) 2020-2024 Aditya Shakya <adi1090x@gmail.com>
##
## Set Wallpaper in Hyprland

WALLPAPER="$HOME/Dropbox/wallpapers/dock-21-9.jpg"

swaybg --output '*' --mode fill --image "$WALLPAPER"
