#!/usr/bin/env bash

## Copyright (C) 2020-2024 Aditya Shakya <adi1090x@gmail.com>
##
## Set Wallpaper in Hyprland

WALLPAPER="$HOME/Dropbox/wallpapers/gradient_hue219.png"

swaybg --output '*' --mode fill --image "$WALLPAPER"
