general {
    # This defines how hypridle should lock when you use `on-timeout = lock`
    lock_cmd = pidof hyprlock || hyprlock
    before_sleep_cmd = loginctl lock-session
    after_sleep_cmd = hyprctl dispatch dpms on
}

# dim screen
# listener {
#    timeout = 10
#    on-timeout = light -O && light -S 5
#    on-resume = light -I
# }

# screen off
listener {
    timeout = 500
    on-timeout = hyprctl dispatch dpms off
    on-resume = hyprctl dispatch dpms on
}

# lock screen
# listener {
#    timeout = 10
#    # on-timeout = lock_cmd      # <-- uses general.lock_cmd above
#    on-timeout = hyprctl dispatch dpms off
#    on-resume = hyprctl dispatch dpms on
# }
