# Shell variables
# Generated by 'wal'
wallpaper='/home/evangelist/Pictures/wallpapers/meadow.png'

# Special
background='#191a24'
foreground='#dad3da'
cursor='#dad3da'

# Colors
color0='#191a24'
color1='#9E93A8'
color2='#F0B39C'
color3='#DCA8A3'
color4='#D3B1B5'
color5='#E9C8AE'
color6='#B1B3CD'
color7='#dad3da'
color8='#989398'
color9='#9E93A8'
color10='#F0B39C'
color11='#DCA8A3'
color12='#D3B1B5'
color13='#E9C8AE'
color14='#B1B3CD'
color15='#dad3da'

# FZF colors
export FZF_DEFAULT_OPTS="
    $FZF_DEFAULT_OPTS
    --color fg:7,bg:0,hl:1,fg+:232,bg+:1,hl+:255
    --color info:7,prompt:2,spinner:1,pointer:232,marker:1
"

# Fix LS_COLORS being unreadable.
export LS_COLORS="${LS_COLORS}:su=30;41:ow=30;42:st=30;44:"
